### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
well, we can update that

**Comment by NextTurn** [comment]
The simplest way to update the time span is to remove it.

**Comment by NextTurn** [comment]
I wonder why Sun Microsystems is in the list.

**Comment by oleg-nenashev** [comment]
> I wonder why Sun Microsystems is in the list.

Hudson/Jenkins project was started at Sun, and WinSW was originally a part of its codebase. So I believe  the reference comes from there

**Comment by oleg-nenashev** [comment]
what is the purpose of the formatting change BTW?

**Comment by NextTurn** [comment]
> what is the purpose of the formatting change BTW?

It's a magic convention in most MIT licenses that lines do not start with spaces and have a max length of 80 characters...

**Pull request merged**
