### PR TITLE
Simplify syntax

### LINKED ISSUE #46: WinSW does nothing on unsupported option in args[0]
Proposed behavior: Print help and fail with a non-null error code

### LINKED ISSUE #148: Update log4net packages to 2.0.latest
It would effectively update log4net from `1.2.13` to `1.2.15`. There is no strongly related fixes, but it would be great to have the latest version.

See https://logging.apache.org/log4net/release/release-notes.html

### LINKED ISSUE #211: Create chat in Gitter/whatever?
I am not sure if the chat is really required for this project, but I am ready to create it if somebody would like this communication approach. Just cast your votes in this issue

### LINKED ISSUE #250: Service account password XML parsing issue
A service account I use has an ampersand in its password, WinSW fails to parse the XML when running the `install` option. Given a service account block something like this (note the ampersand in the password field):
````
[snip]
  <serviceaccount>
    <domain>MYDOMAIN</domain>
    <user>svc-account-user</user>
    <password>T1r9_3&</password>
    <allowservicelogon>true</allowservicelogon>
  </serviceaccount>
[snip]
````
I get this error when running install:

````
System.Xml.XmlException: An error occurred while parsing EntityName. Line 28, position 22.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseEntityReference()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at winsw.ServiceDescriptor..ctor()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
````

Removing the ampersand gets rid of the parsing error, but obviously my password is then wrong in the service configuration :)

Thanks in advance for any help!

### PR DESCRIPTION
**Pull request by NextTurn**
Based on #356

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@NextTurn I am not sure how would it close https://github.com/kohsuke/winsw/issues/211  :)

**Comment by NextTurn** [comment]
lol Are you expecting someone to answer that question after nearly three years?

Personally, email or anything else is OK for me. I often talk in issues though.

**Comment by oleg-nenashev** [comment]
@NextTurn I do not expect anyone to respond there, especially since I do not have capacity to maintain the community. Jenkins soaks almost all my time, and it is unlikely to change in short-term. Anyway, the approach with closing unrelated issues via GitHub automation is not what I would prefer. You can just comment in the issues instead, and I will get irrelevant ones closed

**Comment by NextTurn** [comment]
OK I've updated the description.

**Pull request merged**
