### PR TITLE
Migrate to SDK-style projects + Require Visual Studio Community 2019 to build the project

### LINKED ISSUE #149: Migrate projects to MVS 2017 Community Edition
It would just provide some added value in the developer experience

### LINKED ISSUE #261: How to generate winsw_key.snk
Confused about the procedure to generate the winsw_key.snk

IDE: [Visual Studio Community 2013](http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx) (free for open-source projects)  
 7   +* `winsw_key.snk` should be available in the project's root in order to build the executable  
 8   + * You can generate the certificate in "Project Settings/Signing"  
 9   + * The certificate is in <code>.gitignore</code> list. Please do not add it to the repository  

Step 8, don't see Project Settings menu or tab anywhere in VS 2015.  Can someone assist in providing a procedure to creating this file so I can build the project?

### PR DESCRIPTION
**Pull request by NextTurn**
Closes #149 
Closes #261 

A prerequisite to add more TFMs. #337, #344 

Note: This PR does not intend to make any functionality changes.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'd guess the only way to test it is to try it out locally. But thanks a lot for the patches! It makes the code a lot simpler from what I see

**Comment by NextTurn** [comment]
> I'd guess the only way to test it is to try it out locally.

Yes, it's good to try it out on a local machine (the older, the better) to ensure it doesn't break anything.

**Comment by oleg-nenashev** [comment]
https://github.com/kohsuke/winsw/blob/master/DEVELOPER.md will need to be updated as a part of this pull request

**Comment by oleg-nenashev** [comment]
I will try to test it tomorrow before merging. From what I see the approach works well in CI, and the produced binaries work well. So I am really optimistic about this change. Thanks a lot @NextTurn !

**Pull request merged**
